### ISSUE TITLE
Multiple fake services

### ISSUE THREAD

**Issue by jondeandres** [admire93/flask-httpretty#4]
Hi,

I've been reading the code of the library. I think it's only allowed use one flask app at the same time?

Are you considering change this?

Thanks

**Comment by admire93** [comment]
@jondeandres i can support multiple fake app, but i wand to listen more specific reason.

**Comment by jondeandres** [comment]
yah, for some complex projects where we use multiple 3rd service integrations, it'd be nice to fake each service.

In ruby projects we have webmock for this, it'd be awesome having a complete library in python too. https://github.com/bblimke/webmock#rack-responses.

Anyway, good job here, I think it's really useful. Thanks.

**Comment by admire93** [comment]
@jondeandres Thanks :+1: , it can be patched in 1~3 days (include #6). when i close this issue, i'll let you know. :)

**Comment by jondeandres** [comment]
wow!! Thanks @admire93 !!!

**Comment by jondeandres** [comment]
@admire93 one question about the implementation.

Shouldn't easier use https://github.com/gabrielfalcao/HTTPretty#dynamic-responses-through-callbacks, so you can call the flask test_client from the callback and return something like `(resp.status_code, resp.headers, resp.dat)` ?

Cheers.

**Comment by admire93** [comment]
@jondeandres i think,

 1. it is easy to control process when use flask. because it provide many useful tools.
 2. it is cooler and simpler `httpretty.register_app(app, 'http://example.com')` than

```python
httpretty.register_uri(
    httpretty.GET, "https://api.yahoo.com/test",
    body=request_callback)
...
```

**Comment by jondeandres** [comment]
@admire93 I was talking about implement your library using the httpretty callbacks, so they return a response that is generated by flask. I don't know if it's doable or it has any sense.

**Comment by admire93** [comment]
@jondeandres oh, i was misunderstood your point. After multiple app registration, i consider it.
